### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EbiScott**

### CODE REVIEW

**Comment by jamesnottidge** [comment]
Please in future provide a description with each pull request you open.

**Review by jamesnottidge — APPROVED** [review]
Welcome Eworitse!

**Comment by EbiScott** [comment]
I'm sorry i didn't leave a description. Thanks for correcting me on that

**Comment by EbiScott** [comment]
> Please in future provide a description with each pull request you open.

I'm sorry i didn't leave a description. Thanks for correcting me on that

**Pull request merged**
